/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'priceSnapshot' : bigint,
  'size' : string,
  'productId' : bigint,
  'quantity' : bigint,
}
export interface ContactMessage {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'sizes' : Array<string>,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
}
export interface _SERVICE {
  'addToCart' : ActorMethod<[bigint, string, bigint], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'getAllContacts' : ActorMethod<[], Array<ContactMessage>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getProductById' : ActorMethod<[bigint], Product>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'submitContact' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];